name: "Pytest - run tests"
description: "run-tests"

inputs:
  test_target:
    description: 'the target folder for the tests'
    required: false
    default: 'tests/unit'

runs:
  using: "composite"
  steps:
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Dependencies
      shell: bash
      run: |          
        pip install -r requirements-test.txt

    - name: Run pytest tests on target folder
      shell: bash
      run: |
        coverage run --source=${{env.PACKAGE_NAME}} -m pytest -v -s --durations=0 ${{inputs.test_target}}

    - name: Print coverage report
      shell: bash
      run: |
        coverage report -m