name       : Publish to PyPI
description: 'Publish to PyPI'

runs:
    using: 'composite'
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        shell: bash
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      - name: Build the package
        shell: bash
        run: | 
          poetry build

      # see issue https://github.com/pypa/gh-action-pypi-publish/issues/290
      #- name: Publish distribution 📦 to PyPI
      #  uses: pypa/gh-action-pypi-publish@release/v1
      
      - name: Publish distribution 📦 to PyPI
       uses: pypa/gh-action-pypi-publish@v1.11.0
